import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { LocaleProvider } from '@/i18n/locale-provider'
import { getLocale } from '@/i18n/server'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Smart Accounting',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const locale = getLocale();
  return (
    <html lang="en">
      <body className={inter.className}>
        <LocaleProvider value={locale}>
          <NextTopLoader color='#FB6592' />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <main>
              {children}
            </main>
          </ThemeProvider>
        </LocaleProvider>
      </body>
    </html>
  )
}
